### ISSUE TITLE
More functions for canvas needed

### ISSUE THREAD

**Issue by kingalex11235** [kingalex11235/MeThink#2]
* Refresh/clear canvas
* Chat notification (with sound effect)
* Fade out login/register page

**Comment by davidbang** [comment]
also add automatic chat scrolling

**Comment by davidbang** [comment]
var myDiv = document.getElementById("big-div");
myDiv.scrollTop = myDiv.scrollHeight;

http://stackoverflow.com/questions/16134257/getting-an-overflowauto-element-to-auto-scroll

**Comment by davidbang** [comment]
clear canvas button is working but need server to clear canvas for all users and not just the one user that presses it.

**Comment by davidbang** [comment]
timer, error login msg x box, chat bottom scroll

**Comment by davidbang** [comment]
http://stackoverflow.com/questions/20618355/the-simplest-possible-javascript-countdown-timer

**Comment by davidbang** [comment]
need video

**Comment by davidbang** [comment]
http://stackoverflow.com/questions/2546857/why-align-center-not-overriding-on-text-alignright


div align = center

**Comment by davidbang** [comment]
glow canvas when turn, start game

**Comment by davidbang** [comment]
messge that person won, close sockets.

**Comment by davidbang** [comment]
message box
